name: Deploy-ManagementAnalyticDashboardWeb

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: odenigbogodfrey/quick-pay:latest
  
  redeploy_aple:
    runs-on: ubuntu-latest
    name: Redeploy webhook call
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: http://164.92.155.135:9101/hooks/quick-pay
          data: ""
  redeploy_benin:
    runs-on: ubuntu-latest
    name: Redeploy webhook call
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          #WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          WEBHOOK_URL: http://67.205.169.2:9101/hooks/quick-pay
          data: ""